#!/usr/bin/env python
# -*- coding: utf-8 -*-


saludo = "Hola"
numero = 4
booleano = True
print(type(saludo))
print(type(numero))
print(type(booleano))
a = 10/3
a= float(a)
a= a + 2.6
print(a)
#print(int(a))
print(type(a))
print(float(45*2))

#calle =" solis"
#nro = 345

#print("Mi direccion es " +calle+ " " +str(nro))

calle= input ("Ingrese el nomnre de la calle: ")
nro= input ("Ingrese la altura: ")
edad = input("Ingrese su edad: ")
edad = int(edad)
print("Su direcciòin y su edad son: " +calle+ " " +str(nro)+ " " +edad)




    
